language: node_js
node_js: 9

script:
  - cd website
  - yarn
  - yarn build

deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: website/build/blessing-skin-plugin-docs
  email: gplane@protonmail.com
  name: GPlane Fans
