version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run: 
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "GPlane Fans@users.noreply.github.com"
            git config --global user.name "GPlane Fans"
            echo "machine github.com login \"GPlane Fans\" password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER="GPlane Fans" yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website
