version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:8

    steps:
      - add_ssh_keys:
          fingerprints: 25:a6:4a:ad:59:0f:56:6d:b7:3e:32:08:10:e8:d7:4c
      - run: echo "  StrictHostKeyChecking no" >> ~/.ssh/config
      - checkout
      - run: 
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "g-plane@hotmail.com"
            git config --global user.name "Pig Fang"
            cd website && yarn install && GIT_USER="Pig Fang" USE_SSH=true yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website
